version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"

  logger:
    container_name: logger
    image: ghcr.io/nameless-coder/factory-production-logger:latest
    restart: always
    ports:
      - 8000:8000
