version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "long password"

  scraper:
    container_name: logger
    image: logger
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
