name: PR CI Image Build
on: pull_request
jobs:
  build-image:
    name: Build Docker and push image
    runs-on: ubuntu-latest
    env:
      GHCR_PAT: ${{secrets.GHCR_PAT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/nameless-coder/factory-production-logger
          tags: |
            type=sha,prefix=pr-
          flavor: |
            latest=false
            prefix=
            suffix=
          labels: |
            org.opencontainers.image.vendor=Nameless Coder
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
